[2025-03-20T08:07:20.263+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T08:07:20.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_scrape_links.Selenium_scrapper manual__2025-03-20T08:07:13.706517+00:00 [queued]>
[2025-03-20T08:07:20.375+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_scrape_links.Selenium_scrapper manual__2025-03-20T08:07:13.706517+00:00 [queued]>
[2025-03-20T08:07:20.376+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-20T08:07:20.417+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Selenium_scrapper> on 2025-03-20 08:07:13.706517+00:00
[2025-03-20T08:07:20.438+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_scrape_links', 'Selenium_scrapper', 'manual__2025-03-20T08:07:13.706517+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_scrape_links.py', '--cfg-path', '/tmp/tmpeco36r5e']
[2025-03-20T08:07:20.436+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=637) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-20T08:07:20.444+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask Selenium_scrapper
[2025-03-20T08:07:20.444+0000] {standard_task_runner.py:72} INFO - Started process 638 to run task
[2025-03-20T08:07:20.567+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_scrape_links.Selenium_scrapper manual__2025-03-20T08:07:13.706517+00:00 [running]> on host 7795c5e0753c
[2025-03-20T08:07:20.881+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_scrape_links' AIRFLOW_CTX_TASK_ID='Selenium_scrapper' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T08:07:13.706517+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T08:07:13.706517+00:00'
[2025-03-20T08:07:20.885+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-20T08:07:22.739+0000] {selenium_manager.py:138} WARNING - The chromedriver version (113.0.5672.63) detected in PATH at /usr/local/bin/chromedriver might not be compatible with the detected chrome version (134.0.6998.117); currently, chromedriver 134.0.6998.90 is recommended for chrome 134.*, so it is advised to delete the driver in PATH and retry
[2025-03-20T08:07:25.280+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/scrape_links.py", line 18, in scrape_pdf_links
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 134.0.6998.117 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x5570ce22f133 <unknown>
#1 0x5570cdf63966 <unknown>
#2 0x5570cdf915ec <unknown>
#3 0x5570cdf8c8da <unknown>
#4 0x5570cdf8907b <unknown>
#5 0x5570cdfc89ad <unknown>
#6 0x5570cdfc818f <unknown>
#7 0x5570cdfbf9a3 <unknown>
#8 0x5570cdf9446a <unknown>
#9 0x5570cdf9555e <unknown>
#10 0x5570ce1eecae <unknown>
#11 0x5570ce1f28fe <unknown>
#12 0x5570ce1fbf20 <unknown>
#13 0x5570ce1f3923 <unknown>
#14 0x5570ce1c6c0e <unknown>
#15 0x5570ce216b08 <unknown>
#16 0x5570ce216c97 <unknown>
#17 0x5570ce227113 <unknown>
#18 0x7f597d9eb1c4 <unknown>

[2025-03-20T08:07:25.557+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_scrape_links, task_id=Selenium_scrapper, run_id=manual__2025-03-20T08:07:13.706517+00:00, execution_date=20250320T080713, start_date=20250320T080720, end_date=20250320T080725
[2025-03-20T08:07:25.588+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-20T08:07:25.589+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task Selenium_scrapper (Message: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 134.0.6998.117 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x5570ce22f133 <unknown>
#1 0x5570cdf63966 <unknown>
#2 0x5570cdf915ec <unknown>
#3 0x5570cdf8c8da <unknown>
#4 0x5570cdf8907b <unknown>
#5 0x5570cdfc89ad <unknown>
#6 0x5570cdfc818f <unknown>
#7 0x5570cdfbf9a3 <unknown>
#8 0x5570cdf9446a <unknown>
#9 0x5570cdf9555e <unknown>
#10 0x5570ce1eecae <unknown>
#11 0x5570ce1f28fe <unknown>
#12 0x5570ce1fbf20 <unknown>
#13 0x5570ce1f3923 <unknown>
#14 0x5570ce1c6c0e <unknown>
#15 0x5570ce216b08 <unknown>
#16 0x5570ce216c97 <unknown>
#17 0x5570ce227113 <unknown>
#18 0x7f597d9eb1c4 <unknown>
; 638)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/scrape_links.py", line 18, in scrape_pdf_links
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 134.0.6998.117 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x5570ce22f133 <unknown>
#1 0x5570cdf63966 <unknown>
#2 0x5570cdf915ec <unknown>
#3 0x5570cdf8c8da <unknown>
#4 0x5570cdf8907b <unknown>
#5 0x5570cdfc89ad <unknown>
#6 0x5570cdfc818f <unknown>
#7 0x5570cdfbf9a3 <unknown>
#8 0x5570cdf9446a <unknown>
#9 0x5570cdf9555e <unknown>
#10 0x5570ce1eecae <unknown>
#11 0x5570ce1f28fe <unknown>
#12 0x5570ce1fbf20 <unknown>
#13 0x5570ce1f3923 <unknown>
#14 0x5570ce1c6c0e <unknown>
#15 0x5570ce216b08 <unknown>
#16 0x5570ce216c97 <unknown>
#17 0x5570ce227113 <unknown>
#18 0x7f597d9eb1c4 <unknown>

[2025-03-20T08:07:25.662+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-20T08:07:25.707+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T08:07:25.712+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
