[2025-03-19T06:38:55.377+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T06:38:55.406+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_mistralAi.etl_mistralAi manual__2025-03-19T06:38:41.338073+00:00 [queued]>
[2025-03-19T06:38:55.418+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_mistralAi.etl_mistralAi manual__2025-03-19T06:38:41.338073+00:00 [queued]>
[2025-03-19T06:38:55.419+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-19T06:38:55.439+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mistralAi> on 2025-03-19 06:38:41.338073+00:00
[2025-03-19T06:38:55.466+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-19T06:38:55.468+0000] {standard_task_runner.py:72} INFO - Started process 520 to run task
[2025-03-19T06:38:55.467+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_mistralAi', 'etl_mistralAi', 'manual__2025-03-19T06:38:41.338073+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_mistralai.py', '--cfg-path', '/tmp/tmp10g59imq']
[2025-03-19T06:38:55.470+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask etl_mistralAi
[2025-03-19T06:38:55.592+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_mistralAi.etl_mistralAi manual__2025-03-19T06:38:41.338073+00:00 [running]> on host 57e1e7414cf2
[2025-03-19T06:38:55.757+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_etl_mistralAi' AIRFLOW_CTX_TASK_ID='etl_mistralAi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T06:38:41.338073+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T06:38:41.338073+00:00'
[2025-03-19T06:38:55.759+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-19T06:38:56.659+0000] {_client.py:1026} INFO - HTTP Request: POST https://api.mistral.ai/v1/ocr "HTTP/1.1 401 Unauthorized"
[2025-03-19T06:38:56.661+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_etl_mistralai.py", line 12, in process_meatadata_links
    ocrResponse = ocr_response(link)
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/etl_mistralAi.py", line 36, in ocr_response
    raise e  # Raise error if it's not rate limit-related
    ^^^^^^^
  File "/opt/airflow/dags/utils/etl_mistralAi.py", line 25, in ocr_response
    return client.ocr.process(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mistralai/ocr.py", line 109, in process
    raise models.SDKError(
mistralai.models.sdkerror.SDKError: API error occurred: Status 401
{
  "message":"No API key found in request",
  "request_id":"4b295b182e076437c4f02322bfff4a1d"
}
[2025-03-19T06:38:56.688+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_etl_mistralAi, task_id=etl_mistralAi, run_id=manual__2025-03-19T06:38:41.338073+00:00, execution_date=20250319T063841, start_date=20250319T063855, end_date=20250319T063856
[2025-03-19T06:38:56.715+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-19T06:38:56.716+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task etl_mistralAi (API error occurred: Status 401
{
  "message":"No API key found in request",
  "request_id":"4b295b182e076437c4f02322bfff4a1d"
}; 520)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_etl_mistralai.py", line 12, in process_meatadata_links
    ocrResponse = ocr_response(link)
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/etl_mistralAi.py", line 36, in ocr_response
    raise e  # Raise error if it's not rate limit-related
    ^^^^^^^
  File "/opt/airflow/dags/utils/etl_mistralAi.py", line 25, in ocr_response
    return client.ocr.process(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mistralai/ocr.py", line 109, in process
    raise models.SDKError(
mistralai.models.sdkerror.SDKError: API error occurred: Status 401
{
  "message":"No API key found in request",
  "request_id":"4b295b182e076437c4f02322bfff4a1d"
}
[2025-03-19T06:38:56.755+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T06:38:56.802+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T06:38:56.811+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
